apiVersion: securityenforcement.admission.cloud.ibm.com/v1beta1
kind: ClusterImagePolicy
metadata:
  name: docker-image-policy
spec:
  repositories:
  - name: docker.io/*
    policy:
      va:
        enabled: false
